#!/bin/bash
find -iname "*.h" -or -iname "*.c" -or -iname "*.s" -or -name Makfile > cscope.files
find ../mylib -iname "*.h" -or -iname "*.c" -or -iname "*.s" -or -name Makfile >> cscope.files
find /opt/Freescale/KDS_v3/eclipse/ProcessorExpert/Repositories/KSDK120_Repository/lib/Kinetis/pdd2/MKL25Z128LK4_4SDK/ -iname "*.h" -or -iname "*.c" -or -iname "*.s" -or -name Makfile >> cscope.files
cscope -b
ctags -L ./cscope.files
